[package]
name = "signaturize"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
signaturize_derive = { version = "0.1.0" }

[dev-dependencies]
signaturize_derive = { path = "../signaturize_derive" }
